name: Update Season Database

on:
  schedule:
    - cron: "0 15 * * *"

jobs:
  update-db:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: "Create env file"
        run: echo "${{secrets.ENV_FILE}}" > .env

      - name: Build TypeScript
        run: npm run build

      - name: Run script
        run: npx tsx ./src/services/updateDb.ts
